# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.public]
file = "src/schemas/public.rs"
schema = "public"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[print_schema.auth]
file = "src/schemas/auth.rs"
schema = "auth"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "migrations"
