version: '3.9'

services:
  pg_index_db:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: default_password
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: host
  joogle:
    build: .
    command: ["/usr/local/bin/joogle"]
    network_mode: host

volumes:
  db_data:
    driver: local

